wilson/SoftParking/SoftParking/SoftParking/Models/servicio.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftParking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class servicio
    {
        public servicio()
        {
            this.detalle_pago = new HashSet<detalle_pago>();
        }
    
        public int codi_serv { get; set; }
        public System.DateTime fech_serv { get; set; }
        public System.TimeSpan hora_entr { get; set; }
        public Nullable<System.DateTime> fech_sali { get; set; }
        public Nullable<System.TimeSpan> hora_sali { get; set; }
        public int codi_empl { get; set; }
        public string plac_vehi { get; set; }
        public int codi_ubic { get; set; }
    
        public virtual ICollection<detalle_pago> detalle_pago { get; set; }
        public virtual empleado empleado { get; set; }
        public virtual vehiculo vehiculo { get; set; }
        public virtual ubicacion ubicacion { get; set; }
    }
}

wilson/SoftParking/SoftParking/SoftParking/Controllers/pagosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SoftParking.Models;
using SoftParking.Clases;

namespace SoftParking.Controllers
{
  public class pagosController : Controller
  {
    private parqueaderoEntities db = new parqueaderoEntities();
    private parqueaderoEntities dbac = new parqueaderoEntities();
    // GET: pagos
    public ActionResult Index()
    {
      return View(db.pago.ToList());
    }


    //vista de pagos 
    public ActionResult Create(int? codServ, string Placa)
    {
      ViewBag.estado = Placa;
      if (Placa != null)
      {
        try
        {
          CalcularPrecioXminuto calcularT = new CalcularPrecioXminuto();
          int IVA = 16;
          string tiempoT = "SELECT  timediff(timestamp(CONCAT(fech_sali, ' ', hora_sali)), timestamp(CONCAT(fech_serv, ' ', hora_entr))) as diferencia from servicio where plac_vehi='" + Placa + "' and codi_serv='" + codServ + "'  and   fech_sali is not null and hora_sali is not null";

          var comprobacion = db.Database.SqlQuery<string>(tiempoT).FirstOrDefault();
          // el resultado lo transformo a tiempo

          TimeSpan tiempoTotal = TimeSpan.Parse(comprobacion);
          //valor por minuto 
          //obtenemos el valor del tipo de vehiculo 
          string TarifaVehi = "select  tari_vehi from  tipo_vehiculo  join vehiculo on tipo_vehiculo.tipo_vehi =vehiculo.tipo_vehi where plac_vehi='" + Placa + "'";
          var consultaTarifa = db.Database.SqlQuery<string>(TarifaVehi).FirstOrDefault();
          double precio = double.Parse(consultaTarifa);
          double valorTiempo = calcularT.ValorMinuto(tiempoTotal, precio);
          double porcentajeIva = (valorTiempo * IVA) / 100;
          double ValorAPagar = (porcentajeIva + valorTiempo);
          /*----*facturacion*----*/

          ViewBag.PlacasPago = Placa;
          ViewBag.CodiServicio = codServ;
          ViewBag.TiempoTotal = comprobacion;
          ViewBag.valorTiempo = valorTiempo;
          ViewBag.porcentajeIva = porcentajeIva;
          ViewBag.ValorAPagar = ValorAPagar;

          /*----*Datos Adicionales*----*/
          //TIPOVEHICULO
          var consultaVehi = db.Database.SqlQuery<string>("select nomb_vehi from tipo_vehiculo join vehiculo on tipo_vehiculo.tipo_vehi = vehiculo.tipo_vehi where vehiculo.plac_vehi='" + Placa + "'").FirstOrDefault();
          double precioMin = precio / 60;
          ViewBag.TipoVehiculo = consultaVehi;
          ViewBag.PrecioVehi = precio;
          ViewBag.PrecioMin = precioMin;
          ViewBag.ConsultaTarifa = consultaTarifa;

        }
        catch (Exception e)
        {


        }
      }
      else
      {

      }
      return View();
    }

    // Generacion de pago  cliente ocasional 
    public ActionResult Gpagos()
    {
      return View();

    }


    [HttpPost]
    public ActionResult Gpagos(int? consecutivo, TimeSpan tiempoTotal, string ValorTiemp, DateTime fecha, int numFacServ, string metodo_pago, double ivaPago, double totalAPagar, string placa)
    {

      pago TablaPago = new pago();
      detalle_pago TabladetaleP = new detalle_pago();

      try
      {
        //insertar pagos           


        TablaPago.codi_pago = consecutivo.GetValueOrDefault();
        TablaPago.nume_fact = numFacServ;
        TablaPago.tipo_pago = metodo_pago;
        TablaPago.fech_pago = fecha;
        TablaPago.iva_pago = (int)ivaPago;
        TablaPago.tota_pago = totalAPagar;
        db.pago.Add(TablaPago);
        db.SaveChanges();

        string CodigoPago = db.Database.SqlQuery<string>("select codi_pago from pago where nume_fact = '" + numFacServ + "'").FirstOrDefault();
        int codigosservTpago = int.Parse(CodigoPago);

        TabladetaleP.idet_pago = consecutivo.GetValueOrDefault();
        TabladetaleP.nume_fact = numFacServ;
        TabladetaleP.tiem_tota = tiempoTotal;
        TabladetaleP.tota_deta = int.Parse(ValorTiemp);
        TabladetaleP.codi_serv = numFacServ;
        TabladetaleP.codi_pago = codigosservTpago;
        db.detalle_pago.Add(TabladetaleP);
        db.SaveChanges();

        ViewBag.ttota = tiempoTotal;
        ViewBag.valtiem = ValorTiemp;
        ViewBag.fechTa = fecha;
        ViewBag.numserv = numFacServ;
        ViewBag.metpag = metodo_pago.ToUpper();
        ViewBag.eliva = ivaPago;
        ViewBag.totapag = totalAPagar;
        ViewBag.Placa = placa;


      }
      catch (Exception e)
      {

      }
      return View();
    }
    
    public ActionResult facturaIngreso(string placaVehiculo)
    {
      if (placaVehiculo != null)
      {
        try
        {
          var codigodeServicio = dbac.Database.SqlQuery<string>("select codi_serv from servicio  where plac_vehi ='" + placaVehiculo.ToUpper() + "' and fech_sali is null  and   hora_sali is NULL").FirstOrDefault();
          int numero = int.Parse(codigodeServicio);
          var CodVahia = dbac.Database.SqlQuery<string>("select codi_ubic from servicio where plac_vehi='" + placaVehiculo + "' and fech_sali is null and hora_sali is null").FirstOrDefault();

          string Piso = "select piso_ubic from   ubicacion where codi_ubic = '" + CodVahia + "'";
          string distintivo = "select dist_ubic from   ubicacion where codi_ubic = '" + CodVahia + "'";

          var CODUBICAPISO = dbac.Database.SqlQuery<string>(Piso).FirstOrDefault();
          var CODUBICALETRA = dbac.Database.SqlQuery<string>(distintivo).FirstOrDefault();

          ViewBag.idServicio = numero;
          ViewBag.placa = placaVehiculo.ToUpper();
          ViewBag.pisoUbicacion = CODUBICAPISO;
          ViewBag.distintivo = CODUBICALETRA;
          ViewBag.CodVahia = CodVahia;
          ViewBag.fechaIng = DateTime.Now;
        }
        catch (Exception e)
        {
          return HttpNotFound();
        }
      }
      return View();
    }
    protected override void Dispose(bool disposing)
    {
      if (disposing)
      {
        db.Dispose();
      }
      base.Dispose(disposing);
    }
  }
}

wilson/SoftParking/SoftParking/SoftParking/Controllers/serviciosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SoftParking.Models;

namespace SoftParking.Controllers
{
  public class serviciosController : Controller
  {
    private parqueaderoEntities db = new parqueaderoEntities();

    // GET: servicios
    public ActionResult Index()
    {

      var tiempo = db.Database.SqlQuery<List<string>>("SELECT  timediff(timestamp(CONCAT(fech_sali, ' ', hora_sali)), timestamp(CONCAT(fech_serv, ' ', hora_entr))) as diferencia from servicio where fech_sali is not null and hora_sali is not null").FirstOrDefault();

      return View(db.servicio.ToList());
    }

    // GET: servicios/Details/5
    public ActionResult Details(int? id)
    {
      if (id == null)
      {
        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
      }
      servicio servicio = db.servicio.Find(id);
      if (servicio == null)
      {
        return HttpNotFound();
      }
      return View(servicio);
    }

    // GET: servicios/Create
    public ActionResult Create()
    {
      ViewBag.codi_empl = new SelectList(db.empleado, "codi_empl", "nomb_empl");
      ViewBag.plac_vehi = new SelectList(db.vehiculo, "plac_vehi", "colo_vehi");
      ViewBag.codi_ubic = new SelectList(db.ubicacion, "codi_ubic", "tama_ubic");
      ViewBag.tipo_vehi = new SelectList(db.tipo_vehiculo, "tipo_vehi", "nomb_vehi");

      //SENTENCIAS QUERYS PARA REALIZAR LA CONSULTA 
      var consulta = "select count(*) from ubicacion";
      var disp = "select count(*) from ubicacion where  esta_ubic='DISPONIBLE'";
      var ocup = "select count(*) from ubicacion where  esta_ubic='OCUPADO'";
      var valor = db.Database.SqlQuery<string>(consulta).FirstOrDefault();
      ViewBag.vahias = valor;
      ViewBag.disponible = db.Database.SqlQuery<string>(disp).FirstOrDefault();
      ViewBag.ocupado = db.Database.SqlQuery<string>(ocup).FirstOrDefault();


      return View();
    }
    
    [HttpPost]
    [ValidateAntiForgeryToken]
    [AcceptVerbs(HttpVerbs.Post)]
    //el parametro int? es  para indicarle  que es un tipo de dato opcional como la tabla  es un autoincremental  no es necesario asignarle valores 
    public ActionResult Create(int? codi_serv, string fech_serv, string hora_entr, int codi_empl, string plac_vehi, int tipo_vehi, int? AuxConsecutivo)
    {  //busca un espacio disponibe 

      var dipo = db.Database.SqlQuery<string>("select count(*) from ubicacion where  esta_ubic='DISPONIBLE'").FirstOrDefault();

      //VErifica  el doble ingreso del  vehiculo en la area  de  servicio 
      var placaDupli = db.Database.SqlQuery<string>("select plac_vehi from servicio  where plac_vehi='" + plac_vehi + "' and  fech_sali is null and hora_sali is null;").FirstOrDefault();
      //instancia de la clase servicio
      servicio serv = new servicio();
      int esp = int.Parse(dipo);

      if (esp != 0)
      {
        try
        {
          // select al cliente generico   alojado en la base de datos 
          var ClienteGenerico = db.Database.SqlQuery<List<string>>("SELECT * FROM cliente WHERE iden_clie='99'").FirstOrDefault();
          //selecciona el primer registro del consecutivo de la base de datos  para ingresar el primer espacio disponible  
          var tam_Vahias = db.Database.SqlQuery<string>("select codi_ubic from ubicacion  where esta_ubic='DISPONIBLE'  ORDER BY codi_ubic ASC limit 1").FirstOrDefault();
          //si las placas  del cliente  no existe en la base de datos el sistema creara uno generico si existe salta este paso 
          var clienteGenerico = db.Database.SqlQuery<List<string>>("SELECT plac_vehi from vehiculo join cliente  on vehiculo.codi_clie=cliente.codi_clie  where vehiculo.plac_vehi='" + plac_vehi.ToUpper() + "' AND cliente.iden_clie='99'").FirstOrDefault();
          //consulta para hallar un cliente registrado
          var clienteRegistro = db.Database.SqlQuery<List<string>>("SELECT plac_vehi from vehiculo join cliente  on vehiculo.codi_clie=cliente.codi_clie  where vehiculo.plac_vehi='" + plac_vehi.ToUpper() + "' AND cliente.iden_clie!='99' and nomb_clie is not null and apel_clie is not null").FirstOrDefault();
          if (ClienteGenerico == null)
          {
            string QUERYINSERT = "insert into cliente (codi_clie,iden_clie,nomb_clie,apel_clie,codi_priv) values (NULL,99,NULL,NULL,'1')";
            db.Database.ExecuteSqlCommand(QUERYINSERT);
            ViewData["ALERTA"] = "NO EXISTE USUARIO GENERICO  EN LA BASE DE DATOS  SE GENERO USUARIO CON CODIGO 99 ";
            return RedirectToAction("Create", "Servicios");
          }
          /********      validacion         *********
          ********    usuario generico   *********/
          else
          {   //si tam_Vahias es nulo=(encontrar espacios disponibles) y la placa de veiculo es nula  le asigna por defecto el usuario generico 99 a la nueva placa   
            if (tam_Vahias != null && clienteGenerico == null && clienteRegistro == null)
            {   //otengo directamente el id del cliente  generico o cliente OCASIONAL para asignarlo 
              string idClient = "select codi_clie from cliente where iden_clie='99'";
              var Idclinet = db.Database.SqlQuery<string>(idClient).FirstOrDefault();
              // realizo un  casting a la consulta tam_Vahias y  lo transformo a un  entero  para luego asignarle  el id de la ubicacion  al servicio a la variable serv.codi_ubic
              int numVahihas = int.Parse(tam_Vahias);
              // insercion de datos a par de las clases de las entidades 
              vehiculo vehi = new vehiculo();
              vehi.plac_vehi = plac_vehi.ToUpper();
              vehi.colo_vehi = null;
              vehi.obse_vehi = null;
              vehi.marc_vehi = null;
              vehi.tipo_vehi = tipo_vehi;
              vehi.codi_clie = int.Parse(Idclinet);
              db.vehiculo.Add(vehi);
              db.SaveChanges();

              //actualizo el estado de la bahia  OCUPADO
              db.Database.ExecuteSqlCommand("UPDATE ubicacion SET esta_ubic = 'OCUPADO' WHERE ubicacion.codi_ubic ='" + numVahihas + "'");

              //crea el nuevo servicio 

              serv.codi_serv = codi_serv.GetValueOrDefault();
              serv.fech_serv = DateTime.Today;
              serv.hora_entr = TimeSpan.ParseExact(hora_entr, "hh\\:mm\\:ss", null);
              serv.codi_empl = codi_empl;
              serv.plac_vehi = plac_vehi.ToUpper();
              serv.codi_ubic = numVahihas;
              db.servicio.Add(serv);
              db.SaveChanges();

              TempData["MSGEXITOSO"] = "EL VEHICULO FUE REGISTRADO SATISFACTORIAMENTE";
              ViewBag.codi_empl = new SelectList(db.empleado, "codi_empl", "nomb_empl", serv.codi_empl);
              ViewBag.plac_vehi = new SelectList(db.vehiculo, "plac_vehi", "colo_vehi", serv.plac_vehi);
              ViewBag.codi_ubic = new SelectList(db.ubicacion, "codi_ubic", "tama_ubic", serv.codi_ubic);

              //bandera para generar el ticket
              TempData["EviarTicket"] = plac_vehi;

              return RedirectToAction("Create");


            }
            //esta validacion es cuando  la placa del cliente generico ya habia sido registrada con anteriorida en la dba
            else if (tam_Vahias != null && clienteGenerico != null && placaDupli == null && clienteRegistro == null)
            {

              int numVahihas = int.Parse(tam_Vahias);
              //actualizo el estado de la bahia  OCUPADO
              db.Database.ExecuteSqlCommand("UPDATE ubicacion SET esta_ubic = 'OCUPADO' WHERE ubicacion.codi_ubic ='" + numVahihas + "'");

              //crea el nuevo servicio 

              serv.codi_serv = codi_serv.GetValueOrDefault();
              serv.fech_serv = DateTime.Today;
              serv.hora_entr = TimeSpan.ParseExact(hora_entr, "hh\\:mm\\:ss", null);
              serv.codi_empl = codi_empl;
              serv.plac_vehi = plac_vehi.ToUpper();
              serv.codi_ubic = numVahihas;//inserta el id  de la vahia al servicio
              db.servicio.Add(serv);
              db.SaveChanges();

              TempData["MSGEXITOSO"] = "EL VEHICULO FUE REGISTRADO SATISFACTORIAMENTE";
              ViewBag.codi_empl = new SelectList(db.empleado, "codi_empl", "nomb_empl", serv.codi_empl);
              ViewBag.plac_vehi = new SelectList(db.vehiculo, "plac_vehi", "colo_vehi", serv.plac_vehi);
              ViewBag.codi_ubic = new SelectList(db.ubicacion, "codi_ubic", "tama_ubic", serv.codi_ubic);

              //bandera para generar el ticket
              TempData["EviarTicket"] = plac_vehi;
              return RedirectToAction("Create");
            }
            else if (tam_Vahias != null && clienteGenerico != null && placaDupli != null)
            {

              TempData["Dobleingreso"] = "EL VEHICULO YA SE ENCUENTRA EN UNA VAHIA ";
              ViewBag.codi_empl = new SelectList(db.empleado, "codi_empl", "nomb_empl", serv.codi_empl);
              ViewBag.plac_vehi = new SelectList(db.vehiculo, "plac_vehi", "colo_vehi", serv.plac_vehi);
              ViewBag.codi_ubic = new SelectList(db.ubicacion, "codi_ubic", "tama_ubic", serv.codi_ubic);

              return RedirectToAction("Create");
            }
            /********      validacion         *********
             ********    usuario registrado   *********/

            //valida que el cliente registrado no se haya insertado anteriormente 
            else if (tam_Vahias != null && clienteRegistro != null && placaDupli == null && clienteGenerico == null)
            {

              int numVahihas = int.Parse(tam_Vahias);
              //actualizo el estado de la bahia  OCUPADO
              db.Database.ExecuteSqlCommand("UPDATE ubicacion SET esta_ubic = 'OCUPADO' WHERE ubicacion.codi_ubic ='" + numVahihas + "'");

              //crea el nuevo servicio 

wilson/SoftParking/SoftParking/SoftParking/Views/Servicios/Create.cshtml
@model SoftParking.Models.servicio
@using SoftParking.Models
@{
  ViewBag.Title = "ASIGNAR SERVICIO";
  var fecha = DateTime.Today.ToString("MM/dd/yyyy");
  var hora = DateTime.Now.ToString("HH:mm:ss");
  var vahias = ViewBag.vahias;
  var disp = ViewBag.disponible;
  var ocup = ViewBag.ocupado;
  var USUARIO = Session["ControlUsuario"] as ControlUsuario;

  var TicketIngreso = TempData["EviarTicket"];
}
@if (USUARIO != null)
{
  <div class="col-lg-offset-6"><img src="~/Imagenes/Banners/Servicios.png" width="392" height="72" /></div>
    <script>
      //script generar hora dinamica
      function updateClock() {
        var currentTime = new Date();
        var currentHours = currentTime.getHours();
        var currentMinutes = currentTime.getMinutes();
        var currentSeconds = currentTime.getSeconds();
        currentHours = (currentHours < 10 ? "0" : "") + currentHours;
        currentMinutes = (currentMinutes < 10 ? "0" : "") + currentMinutes;
        currentSeconds = (currentSeconds < 10 ? "0" : "") + currentSeconds;

        var currentTimeString = currentHours + ":" + currentMinutes + ":" + currentSeconds;


        $("#hora").val(currentTimeString);

      }
      //update cloclk me actualiza la variable en  1 segundo
      $(document).ready(function () {
        setInterval('updateClock()', 1000);
      });
    </script>
    <script>

      $(document).ready(function () {
        $('#Mensaje').modal('show');

      });
    </script>
    <script>
      $(document).ready(function () {
        $('#MensajeExito').hide().show('slow').delay(3000).hide('slow');
      });
    </script>

        <script type="text/javascript">
          window.onload = function () {


            var valortick = document.getElementById("prueba").value;

            if (valortick != null) {
              ejecutar();
            }

          }
          function ejecutar() {
            window.open(href = "@Url.Action("facturaIngreso", "pagos", new { placaVehiculo = TicketIngreso })", "_blank", "toolbar=yes,scrollbars=yes,resizable=yes,top=600,left=600,width=500,height=500");
          }

        </script>



  using (Html.BeginForm())
  {
    @Html.AntiForgeryToken()



        <!--PANEL DE VAHIAS -->
    <div class="jumbotron form-horizontal" style="border:1px solid">
      <div class="center-block">
        <table class="table-bordered" style="margin: 0 auto;">
          <tr class="text-center active">
            <th class="alert-success">
              ESPACIOS TOTALES
            </th>

            <th class="alert-success">
              ESPACIOS DISPONIBLES
            </th>

            <th class="alert-success">
              ESPACIOS OCUPADOS
            </th>
          </tr>
          <tr class="text-center">
            <th class="text-center">
              <input type="text" value="@vahias" disabled />
              @*@vahias*@
            </th>
            <th class="text-center">
              <input type="text" value="@disp" disabled />
              @*@vahias*@
            </th>

            <th class="text-center">
              <input type="text" value="@ocup" disabled />
              @*@vahias*@
            </th>

          </tr>
        </table>
      </div><hr />

      <!-- INICIO   DEL FORMULARIO     -->

      @Html.ValidationSummary(true, "", new { @class = "text-danger" })
      <div class="col-md-6">

        <label for="fechaserv">FECHA</label><br />
        <div>
          <input type="text" class="form-control" name="fech_serv" style="font-size: 15pt;" value="@fecha" readonly />

        </div><br />
        <label>TIPO DE VEHICULO</label><br />
        <div>
          @Html.DropDownList("tipo_vehi", null, htmlAttributes: new { @class = "form-control", @style = "float: left" })
        </div><hr />


        @*-----------------------------------------------------hhhhh-------------------------*@


        @*codigo de usuario*@
        <input type="number" name="codi_empl" value="@USUARIO.UserID" hidden />


      </div>@*termina la columna  con espacios de 6 posciciones*@

      <div class="col-md-offset-6">
        <label for="Mplac" id="placas" size="35">PLACA DEL VEHICULO</label><br />
        <INPUT id=text1 style="WIDTH: 300px; HEIGHT: 100px; font-size: 50pt;text-transform:uppercase;background:yellow " name="plac_vehi" minlength="6" maxlength="6" autocomplete="off" required>
      </div><br />
      <div class="col-md-offset-6" id="Eldiv">
        <label for="Mplac" id="numeros" size="35">HORA</label><br />
        <INPUT type="text" class="text-center" id="hora" style="WIDTH: 300px; HEIGHT: 80px; font-size: 50pt;text-transform:uppercase " name="hora_entr" value="@hora">
      </div><br />



      <div class="form-group">
        <div class="col-md-offset-6">
          <button type="submit" class="btn btn-info" name="Create" value="Create">Registrar Entrada</button>&nbsp;&nbsp;
          <button type="submit" class="btn btn-info" name="Salida" value="Salida" formaction="@Url.Action("Salida","servicios")">Registrar Salida</button>
        </div>
      </div>
      @if (TempData["MSGEXITOSO"] != null)
      {
        <div id="MensajeExito" class="text-center alert-success">@TempData["MSGEXITOSO"] </div>
                <input id="prueba" hidden type="text" value="@TempData["EviarTicket"]" />
      }


      @if (TempData["SinEspacio"] != null)
      {

        <div class="modal fade" id="Mensaje" role="dialog">
          <div class="modal-dialog modal-sm">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title text-danger">SIN ESPACIO</h4>
              </div>
              <div class="modal-body">
                <div class="text-center" style="font-size: 10pt">@TempData["SinEspacio"].</div>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>
      }


      @if (TempData["ServErr"] != null)
      {
        <div class="modal fade" id="Mensaje" role="dialog">
          <div class="modal-dialog modal-sm">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title text-danger "> !ERROR! </h4>
              </div>
              <div class="modal-body">
                <div class="text-center" style="font-size: 10pt">@TempData["ServErr"].</div>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
              </div>
            </div>
          </div>
        </div>
      }

      @if (TempData["Dobleingreso"] != null)
      {
        <div class="modal fade" id="Mensaje" role="dialog">
          <div class="modal-dialog modal-sm">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title text-danger "> !ERROR! </h4>
              </div>
              <div class="modal-body">
                <div class="text-center" style="font-size: 10pt">@TempData["Dobleingreso"]</div>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
              </div>
            </div>
          </div>
        </div>
      }
    </div>
    <div>
      @Html.ActionLink("Back to List", "Index")
    </div>
  }
}

wilson/SoftParking/SoftParking/SoftParking/Views/Servicios/Delete.cshtml
@model SoftParking.Models.servicio

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>servicio</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.fech_serv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fech_serv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.hora_entr)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.hora_entr)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.hora_sali)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.hora_sali)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.empleado.nomb_empl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.empleado.nomb_empl)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.vehiculo.colo_vehi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.vehiculo.colo_vehi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ubicacion.tama_ubic)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ubicacion.tama_ubic)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>