PROYECTOWEB20161108/PROYECTOWEB/PROYECTOWEB/PROYECTOWEB/SoftParking/SoftParking/Controllers/LogeoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SoftParking.Models;

namespace SoftParking.Controllers
{
    public class LogeoController : Controller
    {
        public int variableUsuario=0;

        private parqueaderoEntities db = new parqueaderoEntities();

        public ActionResult login()
        {

            return View();
        }

        [HttpPost]
        public ActionResult login(String usuario, String password)
        {
            var resultado = Validar(usuario, password);

            if (resultado == true)
            {
             
                return RedirectToAction("Index", "Home");
            }
            else {

                ViewBag.fallo = "USUARIO O CONTRASEÑA INCORRECTOS";
                return View();
                ////return RedirectToAction("Error", "Logeo");
            }
          
        }


// funcion    que me  permite  comprobar el  usuario y contraseña 

        private bool Validar(String Usuario, String Password)
        {

            /* empleado empleadoUs =  db.empleado.Single(p => p.usua_empl == Usuario);
             empleado empleadoCon = db.empleado.Single(p => p.cont_empl == Password);
            */
            var query = (from u in db.empleado
                         where u.usua_empl == Usuario && u.cont_empl == Password
                         select u).FirstOrDefault();

            //si la consulta query  es correcta creamos la sesion a ese usuario

            if (query != null) {
                //consulta  para obtener  el id de usuario el nombre  y el rol  si lo encuentra  se asigna y crea una nueva sesion
                var query2 = (from u in db.empleado
                              where u.usua_empl == Usuario && u.cont_empl == Password
                              select u.codi_empl).FirstOrDefault();
                var query3 = (from u in db.empleado
                              where u.usua_empl == Usuario && u.cont_empl == Password
                              select u.usua_empl).FirstOrDefault();

                var query4 = (from u in db.empleado
                              where u.usua_empl == Usuario && u.cont_empl == Password
                              select u.carg_empl).FirstOrDefault();

                //fecha inicio de login 
                var fechainicio= @DateTime.Now.ToLocalTime();

                variableUsuario = query2;

                Session["ControlUsuario"] = new ControlUsuario() { UserID = query2, Usuario = query3, Rol = query4 ,Fecha=fechainicio,iniciaTurno="no"};

                /* Session["UserID"] = query2;
                 Session["Usuario"] = query3;
                */
                return true;
            }

            else { 
                return false;
            }
            
        }





// funcion cierre de sesion de usuario
        public ActionResult logout() {

            
            Session.Clear();
            return RedirectToAction("Index","Home");
        }


       

    }
}

PROYECTOWEB20161108/PROYECTOWEB/PROYECTOWEB/PROYECTOWEB/SoftParking/SoftParking/Controllers/cajasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SoftParking.Models;

namespace SoftParking.Controllers
{
    public class cajasController : Controller
    {
        private parqueaderoEntities db = new parqueaderoEntities();

        // GET: cajas
        public ActionResult Index()
        {
            return View(db.caja.ToList());
        }

        // GET: cajas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            caja caja = db.caja.Find(id);
            if (caja == null)
            {
                return HttpNotFound();
            }
            return View(caja);
        }

        // GET: cajas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: cajas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "codi_caja,nomb_caja,esta_caja,obse_caja")] caja caja)
        {
            if (ModelState.IsValid)
            {
                db.caja.Add(caja);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(caja);
        }

        // GET: cajas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            caja caja = db.caja.Find(id);
            if (caja == null)
            {
                return HttpNotFound();
            }
            return View(caja);
        }

        // POST: cajas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "codi_caja,nomb_caja,esta_caja,obse_caja")] caja caja)
        {
            if (ModelState.IsValid)
            {
                db.Entry(caja).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(caja);
        }

        // GET: cajas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            caja caja = db.caja.Find(id);
            if (caja == null)
            {
                return HttpNotFound();
            }
            return View(caja);
        }

        // POST: cajas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            caja caja = db.caja.Find(id);
            db.caja.Remove(caja);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PROYECTOWEB20161108/PROYECTOWEB/PROYECTOWEB/PROYECTOWEB/SoftParking/SoftParking/Controllers/empleadoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SoftParking.Models;

namespace SoftParking.Controllers
{
    public class empleadoController : Controller
    {
        private parqueaderoEntities db = new parqueaderoEntities();

        // GET: empleado
        public async Task<ActionResult> Index()
        {
            return View(await db.empleado.ToListAsync());
        }

        // GET: empleado/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            empleado empleado = await db.empleado.FindAsync(id);
            if (empleado == null)
            {
                return HttpNotFound();
            }
            return View(empleado);
        }

        // GET: empleado/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: empleado/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "codi_empl,iden_empl,nomb_empl,apel_empl,dire_empl,usua_empl,cont_empl,carg_empl")] empleado empleado)
        {
            if (ModelState.IsValid)
            {   
                db.empleado.Add(empleado);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(empleado);
        }

        // GET: empleado/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            empleado empleado = await db.empleado.FindAsync(id);
            if (empleado == null)
            {
                return HttpNotFound();
            }
            return View(empleado);
        }

        // POST: empleado/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "codi_empl,iden_empl,nomb_empl,apel_empl,dire_empl,usua_empl,cont_empl,carg_empl")] empleado empleado)
        {
            if (ModelState.IsValid)
            {
                db.Entry(empleado).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(empleado);
        }

        // GET: empleado/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            empleado empleado = await db.empleado.FindAsync(id);
            if (empleado == null)
            {
                return HttpNotFound();
            }
            return View(empleado);
        }

        // POST: empleado/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            empleado empleado = await db.empleado.FindAsync(id);
            db.empleado.Remove(empleado);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PROYECTOWEB20161108/PROYECTOWEB/PROYECTOWEB/PROYECTOWEB/SoftParking/SoftParking/Controllers/turnoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SoftParking.Models;
using System.Dynamic;

namespace SoftParking.Controllers
{
    public class turnoController : Controller
    {
        private parqueaderoEntities db = new parqueaderoEntities();


        // GET: turno
        public ActionResult Index()
        {
            //incluye  las referencias empleado y caja ala tabla turno  
            var turno=db.turno.Include(s =>s.empleado).Include(s =>s.caja);
            return View(db.turno.ToList());
        }



        // GET: turno/Create
        [HttpGet]
        public ActionResult Create()
        { /// para un dropdown
            var MisCajas = db.caja.ToList();
            SelectList listaCaja = new SelectList(MisCajas, "codi_caja", "nomb_caja", "Estado");
             ViewBag.VistasCaja = listaCaja;
             ViewBag.ListaCaja = db.caja.ToList();

           // ViewBag.ListaMic = listaCaja;
            /// para  enviar una lista  a la vista desde la  base de datos
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "codi_turn,codi_empl,codi_caja,fech_inic,fech_fina,mont_inic,desc_turn")] turno turno)
        {
            if (ModelState.IsValid)
            {
                db.turno.Add(turno);
                db.SaveChanges();
                //se creo una variable bandera para que cuando se realice el procedimiento sepa que se efectuo correctamente
                string var = "si";
                TempData["BanderaTurno"] = var;
                return RedirectToAction("Index","servicios");

            }

            ViewBag.codi_caja = new SelectList(db.caja, "codi_caja", "nomb_caja", turno.codi_caja);
            ViewBag.codi_empl = new SelectList(db.empleado, "codi_empl", "nomb_empl", turno.codi_empl); 
            return View(turno);
        }




        // POST: turno/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "codi_turn,codi_empl,codi_caja,fech_inic,fech_fina,mont_inic,desc_turn")] turno turno)
        {
            if (ModelState.IsValid)
            {
                db.Entry(turno).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.codi_caja = new SelectList(db.caja, "codi_caja", "nomb_caja", turno.codi_caja);
            ViewBag.codi_empl = new SelectList(db.empleado, "codi_empl", "nomb_empl", turno.codi_empl);
            return View(turno);
        }

        // GET: turno/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            turno turno = db.turno.Find(id);
            if (turno == null)
            {
                return HttpNotFound();
            }
            return View(turno);
        }

        

        // GET: turno/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            turno turno = db.turno.Find(id);
            if (turno == null)
            {
                return HttpNotFound();
            }
            ViewBag.codi_empl = new SelectList(db.empleado, "codi_empl", "nomb_empl", turno.empleado.codi_empl);
            ViewBag.codi_caja = new SelectList(db.caja, "codi_caja", "nomb_caja", turno.caja.codi_caja);
            return View(turno);
        }

        // POST: turno/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            turno turno = db.turno.Find(id);
            db.turno.Remove(turno);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PROYECTOWEB20161108/PROYECTOWEB/PROYECTOWEB/PROYECTOWEB/SoftParking/SoftParking/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <style>
        .row.content {
            height: auto;
        }
        footer {
            background-color: #555;
            color: white;
            padding: 15px;
        }
      
    </style>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title -  SOFT PARKING</title>
    @using SoftParking.Models;
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/")
    @RenderSection("scripts", required: false)
    <script src="~/Scripts/jquery.slides.min.js" type="text/javascript"></script>
    <script src="~/Scripts/bootbox.min.js" type="text/javascript"></script>
    <script src="~/Content/javascript/ScripNavegacionLat.js" type="text/javascript"></script>
    <link rel="stylesheet" href="~/Content/javascript/NavegacionLateral.css">
    <link rel="stylesheet" href="~/Content/javascript/NavegacionSuperior.css">
    <!-- inicio de sesion -->
    @{
        var USUARIO = Session["ControlUsuario"] as ControlUsuario;
       
    }

</head>

@if (USUARIO != null)
{
    
    <body>
        <header>
            <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
                <div class="container-fluid">
                    <div class="navbar-header navbar-right">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#Barra">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-btn"><img src="~/Imagenes/softparkingSmall.png" alt="logo" width="45"></img></a>
                    </div>
                    <div>
                        <div class="collapse navbar-collapse navbar-right" id="Barra">
                            <ul class="nav navbar-nav navbar-header">
                                <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                                <li>@Html.ActionLink("NuestraEmpresa", "NuestraEmpresa", "Home")</li>
                                <li>@Html.ActionLink("Politicas", "Politicas", "Home")</li>
                                <li>@Html.ActionLink("Nuestra Historia", "Historia", "Home")</li>
                                <li>@Html.ActionLink("Contactenos", "Contactenos", "Home")</li>
                                <li><a> @USUARIO.Usuario</a></li>
                                <li><a href="@Url.Action("logout","Logeo")"><span class="glyphicon glyphicon-log-in"></span>Logout</a></li>                  
                              </ul>                     
                        </div><!-- fin nav collapse -->
                    </div>
                </div>
            </nav>
          
        </header>
        
            <!-- columna izquierda  incluir barra de navegacion lateral -->
        <div class="row content">
            <div class="col-sm-2 sidenav">
                
                    <nav class="navbar navbar-inverse sidebar navbar-static-top " role="navigation" id="Barra2">
                        <div class="container-fluid">
                            <div class="navbar-header navbar-right">
                                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#Barra_iz">
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </button>
                         
                            </div> 
                                <div class="collapse navbar-collapse" id="Barra_iz">
                                    <!-- Brand and toggle get grouped for better mobile display  cabecera -->
                                    <div class="navbar-header">
                                        <a class="navbar-brand"></a>
                                    </div>
                                    <!-- Barra de navegacion para enlazar las vistas -->
                                    <ul class="nav navbar-nav ">
                                        <li class="active"><a href="@Url.Action("Index", "Home")">Inicio<span style=" font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-home"></span></a></li>
                                        <li><a href="@Url.Action("Index", "empleado")">USUARIOS<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-user"></span></a></li>
                                        <li><a href="@Url.Action("Index", "turno")">INICIAR TURNO<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-hourglass"></span></a></li>
                                        <li><a href="@Url.Action("Index", "cajas")">CAJAS<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-inbox"></span></a></li>
                                        <li><a href="@Url.Action("Create", "servicios")">SERVICIO<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-scale"></span></a></li> 
                                        <li><a href="@Url.Action("Create", "ubicacion")">UBICACIONES<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-book"></span></a></li>
                                        <li><a href="@Url.Action("Index", "Configuracion")">CONFIGURACION<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-cog"></span></a></li>
                                    </ul>
                                </div>
                            </div>
                    </nav>
                    <!-- fin de la barra de navegacion lateral  -->
                
            </div>
            
            <!-- columna central para agregar el contenido de la pagina  -->
            <div class="col-sm-8 text-left">
                <div class="container-fluid">
                   
                    @RenderBody()
                </div>
            </div>          
            
        </div><!--fin row content   -->
       
         
        <footer class="container-fluid text-center   ">
            <p>Footer Text</p>
        </footer>


    </body>
}
else
{
<h1>PAGINA NO DISPONIBLE</h1>
}
</html>

PROYECTOWEB20161108/PROYECTOWEB/PROYECTOWEB/PROYECTOWEB/SoftParking/SoftParking/Views/Shared/_VistaOperario.cshtml
<!DOCTYPE html>
<html>
<head>

    <style>
        .row.content {
            height: auto;
        }

        footer {
            background-color: #555;
            color: white;
            padding: 15px;
        }
    </style>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>@ViewBag.Title -  SOFT PARKING</title>
    @using SoftParking.Models;
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="~/Scripts/jquery-3.0.0-beta1.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.slides.min.js" type="text/javascript"></script>
    <script src="~/Content/javascript/ScripNavegacionLat.js" type="text/javascript"></script>
    <link rel="stylesheet" href="~/Content/javascript/NavegacionLateral.css">
    <link rel="stylesheet" href="~/Content/javascript/NavegacionSuperior.css">
    <!-- inicio de sesion -->
    @{
        var USUARIO = Session["ControlUsuario"] as ControlUsuario;
    }

</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header navbar-right">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-btn"><img src="~/Imagenes/softparkingSmall.png" alt="logo" width="45"></img></a>
            </div>
            <div class="collapse navbar-collapse navbar-right" id="myNavbar">
                <ul class="nav navbar-nav navbar-header">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("NuestraEmpresa", "NuestraEmpresa", "Home")</li>
                    <li>@Html.ActionLink("Politicas", "Politicas", "Home")</li>
                    <li>@Html.ActionLink("Nuestra Historia", "Historia", "Home")</li>
                    <li>@Html.ActionLink("Contactenos", "Contactenos", "Home")</li>
                    <li><a> @USUARIO.Usuario</a></li>
                    <li><a href="@Url.Action("logout","Logeo")"><span class="glyphicon glyphicon-log-in"></span>Logout</a></li>
                </ul>

            </div>
        </div>
    </nav>

    <!-- columna izquierda  incluir barra de navegacion lateral -->
    <div class="row content">
        <div class="col-sm-2 ">
            <div class="container-fluid">
                <nav class="navbar navbar-inverse sidebar navbar-fixed-top" role="navigation">
                    <div class="container-fluid">
                        <div class="collapse navbar-collapse ">
                            <!-- Brand and toggle get grouped for better mobile display  cabecera -->
                            <div class="navbar-header">
                                <a class="navbar-brand"></a>
                            </div>
                            <!-- Collect the nav links, forms, and other content for toggling -->
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar"></button>
                            <ul class="nav navbar-nav" id="myNavbar">
                                <li class="active"><a href="@Url.Action("Index", "Home")">Inicio<span style=" font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-home"></span></a></li>
                                <li><a href="@Url.Action("Index", "empleado")">USUARIOS OPERARIO<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-user"></span></a></li>
                                <li><a href="#">TURNO<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-envelope"></span></a></li>
                                <li><a href="#">Home<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-home"></span></a></li>
                                <li><a href="#">Profile<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-user"></span></a></li>
                                <li><a href="#">Messages<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-envelope"></span></a></li>
                            </ul>
                        </div>
                    </div>
                </nav>
                <!-- fin de la barra de navegacion lateral  -->
            </div>
        </div>

        <!-- columna central para agregar el contenido de la pagina  -->
        <div class="col-sm-8 text-left">
            <div class="container-fluid">
                @RenderBody()
            </div>
        </div>
        <!-- columna final derecha 2 botones grandes   -->
        <div class="col-sm-2  ">
            <div class="container-fluid">
                <div class="well">
                    <p>la hora es </p>

                    <p>@DateTime.Now.ToLocalTime()</p>
                </div>

                <div class="well">
                    <p>ADS</p>
                </div>
            </div>

            <hr>
        </div>
    </div>

    <footer class="container-fluid text-center   ">
        <p>Footer Text</p>
    </footer>


</body>
</html>